[frontend]
git-tree-sha1 = "15ac3c241da73c5dbbc4b251227c9f1e2292b13d"

    [[frontend.download]]
    sha256 = "b06d9c1ffa8b68310f5dafb915bdee3b0a359eeffad440a5ca32811759a0c694"
    url = "https://github.com/iijlab/NetworkVisualizer.js/archive/refs/tags/v0.0.4.tar.gz"
